name: Sincronizar Obras con Coda

on:
  schedule:
    - cron: '0 5 * * *'  # Se ejecutará todos los días a las 5:00 AM UTC
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  sync_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Si tienes un archivo requirements.txt

      - name: Ejecutar script de sincronización
        env:
          CODA_API_TOKEN: ${{ secrets.CODA_API_TOKEN }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          CODA_DOC_NAME: ${{ secrets.CODA_DOC_NAME }}
          CODA_TABLE_NAME: ${{ secrets.CODA_TABLE_NAME }}
        run: python sync_coda.py